// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc;

public interface findNodeAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.findNodeAnswer)
    com.google.protobuf.MessageOrBuilder {
}
