// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc;

public interface findValueMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.findValueMessage)
    com.google.protobuf.MessageOrBuilder {
}
