// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc;

public final class Kademlia {
  private Kademlia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_pingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_pingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_pingAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_pingAnswer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_storeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_storeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_storeAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_storeAnswer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_findNodeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_findNodeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_findNodeAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_findNodeAnswer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_findValueMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_findValueMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_findValueAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_findValueAnswer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Kademlia.proto\022\rkademlia.grpc\"3\n\013pingM" +
      "essage\022\n\n\002id\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022\014\n\004port\030\003" +
      " \001(\005\"E\n\npingAnswer\022\n\n\002id\030\001 \001(\t\022\n\n\002ip\030\002 \001" +
      "(\t\022\014\n\004port\030\003 \001(\005\022\021\n\ttimestamp\030\004 \001(\t\"\016\n\014s" +
      "toreMessage\"\r\n\013storeAnswer\"\021\n\017findNodeMe" +
      "ssage\"\020\n\016findNodeAnswer\"\022\n\020findValueMess" +
      "age\"\021\n\017findValueAnswer2\253\002\n\017KademliaServi" +
      "ce\022=\n\004Ping\022\032.kademlia.grpc.pingMessage\032\031" +
      ".kademlia.grpc.pingAnswer\022@\n\005Store\022\033.kad" +
      "emlia.grpc.storeMessage\032\032.kademlia.grpc.",
      "storeAnswer\022I\n\010FindNode\022\036.kademlia.grpc." +
      "findNodeMessage\032\035.kademlia.grpc.findNode" +
      "Answer\022L\n\tFindValue\022\037.kademlia.grpc.find" +
      "ValueMessage\032\036.kademlia.grpc.findValueAn" +
      "swerB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kademlia_grpc_pingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kademlia_grpc_pingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_pingMessage_descriptor,
        new String[] { "Id", "Ip", "Port", });
    internal_static_kademlia_grpc_pingAnswer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kademlia_grpc_pingAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_pingAnswer_descriptor,
        new String[] { "Id", "Ip", "Port", "Timestamp", });
    internal_static_kademlia_grpc_storeMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kademlia_grpc_storeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_storeMessage_descriptor,
        new String[] { });
    internal_static_kademlia_grpc_storeAnswer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kademlia_grpc_storeAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_storeAnswer_descriptor,
        new String[] { });
    internal_static_kademlia_grpc_findNodeMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_kademlia_grpc_findNodeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_findNodeMessage_descriptor,
        new String[] { });
    internal_static_kademlia_grpc_findNodeAnswer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_kademlia_grpc_findNodeAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_findNodeAnswer_descriptor,
        new String[] { });
    internal_static_kademlia_grpc_findValueMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_kademlia_grpc_findValueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_findValueMessage_descriptor,
        new String[] { });
    internal_static_kademlia_grpc_findValueAnswer_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_kademlia_grpc_findValueAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_findValueAnswer_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
