// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc;

public interface pingAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.pingAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string ip = 2;</code>
   */
  String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>string timestamp = 4;</code>
   */
  String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
