// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc;

public interface storeAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.storeAnswer)
    com.google.protobuf.MessageOrBuilder {
}
