// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc.builders;

public interface FindValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.builders.FindValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kademlia.grpc.builders.Node sender = 1;</code>
   */
  boolean hasSender();
  /**
   * <code>.kademlia.grpc.builders.Node sender = 1;</code>
   */
  Node getSender();
  /**
   * <code>.kademlia.grpc.builders.Node sender = 1;</code>
   */
  NodeOrBuilder getSenderOrBuilder();

  /**
   * <code>bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>repeated .kademlia.grpc.builders.Node nodes = 3;</code>
   */
  java.util.List<Node>
      getNodesList();
  /**
   * <code>repeated .kademlia.grpc.builders.Node nodes = 3;</code>
   */
  Node getNodes(int index);
  /**
   * <code>repeated .kademlia.grpc.builders.Node nodes = 3;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .kademlia.grpc.builders.Node nodes = 3;</code>
   */
  java.util.List<? extends NodeOrBuilder>
      getNodesOrBuilderList();
  /**
   * <code>repeated .kademlia.grpc.builders.Node nodes = 3;</code>
   */
  NodeOrBuilder getNodesOrBuilder(
      int index);
}
