// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc.builders;

public final class Kademlia {
  private Kademlia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_StoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_StoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_StoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_StoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_FindNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_FindNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_FindNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_FindNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_FindValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_FindValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_FindValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_FindValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kademlia_grpc_builders_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kademlia_grpc_builders_Node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Kademlia.proto\022\026kademlia.grpc.builders" +
      "\";\n\013PingRequest\022,\n\006sender\030\001 \001(\0132\034.kademl" +
      "ia.grpc.builders.Node\"<\n\014PingResponse\022,\n" +
      "\006sender\030\001 \001(\0132\034.kademlia.grpc.builders.N" +
      "ode\"X\n\014StoreRequest\022,\n\006sender\030\001 \001(\0132\034.ka" +
      "demlia.grpc.builders.Node\022\013\n\003key\030\002 \001(\014\022\r" +
      "\n\005value\030\003 \001(\014\"=\n\rStoreResponse\022,\n\006sender" +
      "\030\001 \001(\0132\034.kademlia.grpc.builders.Node\"O\n\017" +
      "FindNodeRequest\022,\n\006sender\030\001 \001(\0132\034.kademl" +
      "ia.grpc.builders.Node\022\016\n\006target\030\002 \001(\014\"m\n",
      "\020FindNodeResponse\022,\n\006sender\030\001 \001(\0132\034.kade" +
      "mlia.grpc.builders.Node\022+\n\005nodes\030\002 \003(\0132\034" +
      ".kademlia.grpc.builders.Node\"M\n\020FindValu" +
      "eRequest\022,\n\006sender\030\001 \001(\0132\034.kademlia.grpc" +
      ".builders.Node\022\013\n\003key\030\002 \001(\014\"P\n\021FindValue" +
      "Response\022,\n\006sender\030\001 \001(\0132\034.kademlia.grpc" +
      ".builders.Node\022\r\n\005value\030\002 \001(\014\"3\n\004Node\022\n\n" +
      "\002id\030\001 \001(\014\022\017\n\007address\030\002 \001(\t\022\016\n\006pubKey\030\003 \001" +
      "(\t2\373\002\n\017KademliaService\022Q\n\004Ping\022#.kademli" +
      "a.grpc.builders.PingRequest\032$.kademlia.g",
      "rpc.builders.PingResponse\022T\n\005Store\022$.kad" +
      "emlia.grpc.builders.StoreRequest\032%.kadem" +
      "lia.grpc.builders.StoreResponse\022]\n\010FindN" +
      "ode\022\'.kademlia.grpc.builders.FindNodeReq" +
      "uest\032(.kademlia.grpc.builders.FindNodeRe" +
      "sponse\022`\n\tFindValue\022(.kademlia.grpc.buil" +
      "ders.FindValueRequest\032).kademlia.grpc.bu" +
      "ilders.FindValueResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kademlia_grpc_builders_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kademlia_grpc_builders_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_PingRequest_descriptor,
        new String[] { "Sender", });
    internal_static_kademlia_grpc_builders_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kademlia_grpc_builders_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_PingResponse_descriptor,
        new String[] { "Sender", });
    internal_static_kademlia_grpc_builders_StoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kademlia_grpc_builders_StoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_StoreRequest_descriptor,
        new String[] { "Sender", "Key", "Value", });
    internal_static_kademlia_grpc_builders_StoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kademlia_grpc_builders_StoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_StoreResponse_descriptor,
        new String[] { "Sender", });
    internal_static_kademlia_grpc_builders_FindNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_kademlia_grpc_builders_FindNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_FindNodeRequest_descriptor,
        new String[] { "Sender", "Target", });
    internal_static_kademlia_grpc_builders_FindNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_kademlia_grpc_builders_FindNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_FindNodeResponse_descriptor,
        new String[] { "Sender", "Nodes", });
    internal_static_kademlia_grpc_builders_FindValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_kademlia_grpc_builders_FindValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_FindValueRequest_descriptor,
        new String[] { "Sender", "Key", });
    internal_static_kademlia_grpc_builders_FindValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_kademlia_grpc_builders_FindValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_FindValueResponse_descriptor,
        new String[] { "Sender", "Value", });
    internal_static_kademlia_grpc_builders_Node_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_kademlia_grpc_builders_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kademlia_grpc_builders_Node_descriptor,
        new String[] { "Id", "Address", "PubKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
