// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Kademlia.proto

package kademlia.grpc.builders;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kademlia.grpc.builders.Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>string address = 2;</code>
   */
  String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string pubKey = 3;</code>
   */
  String getPubKey();
  /**
   * <code>string pubKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getPubKeyBytes();
}
